'use strict';
(()=>{
const TARGET_KEY='smokeLab.dailyTarget';let editingTs=null,lastToday=-1,lastMilestone=0,targetEditing=false;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function todaySmokes(){return S.smokes.filter(x=>sameDay(x.ts,new Date())).sort((a,b)=>b.ts-a.ts)}
function priorAverage(){const days=[];for(let i=1;i<=7;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);days.push(S.smokes.filter(x=>sameDay(x.ts,d)).length)}const active=days.filter(n=>n>0);return active.length?active.reduce((a,b)=>a+b,0)/active.length:null}
function target(){const n=Number(localStorage.getItem(TARGET_KEY));return Number.isFinite(n)&&n>0?n:null}
function sinceLabel(){const last=S.smokes.at(-1);if(!last)return'Noch keine Zigarette erfasst';const ms=Math.max(0,Date.now()-last.ts),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return h?`${h} Std. ${m} Min.`:`${m}:${String(s).padStart(2,'0')} Min.`}
function ensureShell(){const homeEl=document.getElementById('home');if(!homeEl||q('.dash-v2',homeEl))return;[...homeEl.children].forEach(el=>el.classList.add('original-home-v1'));const shell=document.createElement('div');shell.className='dash-v2';shell.innerHTML='<section class="dash-hero" id="dashHero"></section><div class="dash-grid"><section class="dash-card" id="dashProgress"></section><section class="dash-card" id="dashAvoided"></section></div><section class="dash-timeline" id="dashTimeline"></section>';homeEl.prepend(shell)}
function renderTargetEditor(){const box=q('#dashProgress');if(!box)return;box.innerHTML='<div class="label">Tagesziel</div><div class="metric"><input id="targetInput" inputmode="numeric" type="number" min="1" max="100" value="'+(target()||'')+'" style="width:76px;text-align:center;border:1px solid var(--line);border-radius:12px;height:44px;font:inherit;font-weight:900;color:var(--primary)"></div><button id="saveTarget" class="dash-target-btn" type="button">Ziel speichern</button>';q('#targetInput')?.focus()}
function renderDash(){ensureShell();const list=todaySmokes(),count=list.length,t=target(),avg=priorAverage(),avoided=avg===null?null:Math.max(0,Math.round(avg-count));const hero=q('#dashHero');if(hero)hero.innerHTML=`<div class="dash-hero-top"><div><div class="eyebrow">HEUTE</div><div class="h2">Dein Rauchverhalten</div><div class="dash-live">Zeit seit der letzten Zigarette</div></div><div class="dash-kpi"><div id="sinceValue" class="dash-kpi-value">${sinceLabel()}</div><div class="dash-kpi-label">seit letzter</div></div></div><div class="dash-actions"><button id="quickSmoke" class="dash-primary" type="button">Zigarette erfassen</button><button id="adjustTime" class="dash-secondary" type="button">Zeitpunkt anpassen</button></div>`;
if(!targetEditing){const p=q('#dashProgress');if(p)p.innerHTML=`<div class="label">Tagesfortschritt</div><div id="todayCount" class="metric ${count!==lastToday?'dash-count-pop':''}">${count}${t?` / ${t}`:''}</div>${t?`<div class="dash-progress"><span style="width:${Math.min(100,count/t*100)}%"></span></div><div class="sub">${count<=t?`${t-count} bis zum Tagesziel`:`${count-t} über dem Tagesziel`}</div>`:`<div class="sub">Noch kein Tagesziel gesetzt.</div><button id="editTarget" class="dash-target-btn" type="button">Tagesziel festlegen</button>`}`}
const a=q('#dashAvoided');if(a)a.innerHTML=`<div class="label">Vermieden</div><div class="metric">${avoided===null?'–':avoided}</div><div class="sub">${avoided===null?'Noch keine Vergleichsbasis aus früheren Tagen.':`gegenüber deinem bisherigen Tagesdurchschnitt (${avg.toFixed(1)})`}</div>`;
const timeline=q('#dashTimeline');if(timeline)timeline.innerHTML=`<div class="dash-section-head"><b>Letzte Einträge</b><span>${count} heute</span></div><div class="activity-list">${list.length?list.slice(0,5).map(x=>`<div class="activity-row"><div class="activity-time">${clock(x.ts)}</div><div class="activity-copy"><b>${x.trigger||'Zigarette'}</b><span>${[x.need,x.intensity?`Stärke ${x.intensity}/5`:null].filter(Boolean).join(' · ')||'Keine Zusatzangaben'}</span></div><div class="activity-actions"><button class="activity-action" data-edit-smoke="${x.ts}" aria-label="Eintrag bearbeiten" type="button">✎</button><button class="activity-action" data-delete-smoke="${x.ts}" aria-label="Eintrag löschen" type="button">×</button></div></div>`).join(''):'<div class="activity-empty">Heute wurde noch keine Zigarette erfasst.</div>'}</div>`;
if(count!==lastToday)lastToday=count}
function pulseSaved(){const b=q('#quickSmoke');if(!b)return;b.classList.remove('saved');void b.offsetWidth;b.classList.add('saved');if(navigator.vibrate)navigator.vibrate(35)}
function openTimed(){openJournal();setTimeout(()=>{jTimeOpen=true;renderTimeControl()},0)}
const originalSave=saveJournal;saveJournal=function(){if(editingTs!==null){const ts=selectedTimestamp(),idx=S.smokes.findIndex(x=>x.ts===editingTs);if(idx>=0)atomic(d=>{d.smokes[idx]={...d.smokes[idx],ts,trigger:jDraft.trigger,need:jDraft.need,intensity:jDraft.intensity}});editingTs=null;closeJournal();renderAll();renderDash();pulseSaved();toast('Eintrag aktualisiert.');return}originalSave();renderDash();pulseSaved()};
function editSmoke(ts){const item=S.smokes.find(x=>x.ts===ts);if(!item)return;editingTs=ts;jQuick=false;jTimeOpen=false;jStep=0;const d=new Date(item.ts);jDraft={timeMode:'custom',customTime:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,trigger:item.trigger||null,need:item.need||null,intensity:item.intensity||null};renderJournal();journalOverlay.classList.add('open')}
function deleteSmoke(ts){if(!confirm('Diesen Eintrag wirklich löschen?'))return;atomic(d=>{d.smokes=d.smokes.filter(x=>x.ts!==ts)});renderAll();renderDash();toast('Eintrag gelöscht.')}
document.addEventListener('click',e=>{const quick=e.target.closest('#quickSmoke');if(quick){openJournal();return}if(e.target.closest('#adjustTime')){openTimed();return}if(e.target.closest('#editTarget')){targetEditing=true;renderTargetEditor();return}if(e.target.closest('#saveTarget')){const n=Number(q('#targetInput')?.value);if(Number.isFinite(n)&&n>0){localStorage.setItem(TARGET_KEY,String(Math.round(n)));targetEditing=false;renderDash();toast('Tagesziel gespeichert.')}return}const ed=e.target.closest('[data-edit-smoke]');if(ed){editSmoke(Number(ed.dataset.editSmoke));return}const del=e.target.closest('[data-delete-smoke]');if(del){deleteSmoke(Number(del.dataset.deleteSmoke));return}},true);
document.addEventListener('change',e=>{if(e.target.id==='customTime'){jDraft.customTime=e.target.value;jTimeOpen=false;renderTimeControl()}},true);
function live(now){const sv=q('#sinceValue');if(sv)sv.textContent=sinceLabel();const last=S.smokes.at(-1);if(last){const mins=Math.floor((Date.now()-last.ts)/60000);const milestone=[30,60,120,240,480,720].filter(x=>mins>=x).at(-1)||0;if(milestone&&milestone!==lastMilestone){lastMilestone=milestone;sv?.classList.add('milestone-glow');setTimeout(()=>sv?.classList.remove('milestone-glow'),1300)}}requestAnimationFrame(live)}
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderDash()};
ensureShell();renderDash();requestAnimationFrame(live);
})();