'use strict';
(()=>{
const q=(s,r=document)=>r.querySelector(s),TARGET_KEY='smokeLab.dailyTarget';let lastMilestone=0,quickMode='smoke',quickTrigger=null,quickIntensity=3,quickTimeMode='now',quickCustom='',quickTimeOpen=false;
function todaySmokes(){return S.smokes.filter(x=>sameDay(x.ts,new Date())).sort((a,b)=>b.ts-a.ts)}
function todayResists(){return S.resists.filter(x=>sameDay(x.ts,new Date()))}
function target(){const n=Number(localStorage.getItem(TARGET_KEY));return Number.isFinite(n)&&n>0?n:null}
function lastSmoke(){return [...S.smokes].sort((a,b)=>a.ts-b.ts).at(-1)||null}
function sinceMs(){const x=lastSmoke();return x?Math.max(0,Date.now()-x.ts):0}
function sinceParts(){const ms=sinceMs(),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return{h,m}}
function progressCycle(){const ms=sinceMs(),cycle=4*3600000;if(!lastSmoke())return 0;return Math.min(1,(ms%cycle)/cycle)}
function ensureShell(){const home=document.getElementById('home');if(!home||q('.dash-v2',home))return;[...home.children].forEach(el=>el.classList.add('original-home-v1'));const shell=document.createElement('div');shell.className='dash-v2';shell.innerHTML='<section id="quitHero" class="quit-hero"></section><div class="kpi-grid"><section id="kpiToday" class="kpi-card"></section><section id="kpiAvoid" class="kpi-card"></section></div><section id="labInsight" class="lab-card"></section>';home.prepend(shell);const ov=document.createElement('div');ov.id='quickSheetOverlay';ov.className='quick-sheet-overlay';ov.innerHTML='<div id="quickSheet" class="quick-sheet" role="dialog" aria-modal="true"></div>';document.body.appendChild(ov)}
function renderHero(){const p=sinceParts(),hero=q('#quitHero');if(!hero)return;hero.innerHTML=`<div class="quit-top"><div class="quit-copy"><div class="eyebrow">RAUCHFREI-TRACKER</div><div class="quit-title">Zeit seit der letzten Zigarette</div><div class="quit-sub">Jede Unterbrechung macht dein Muster sichtbarer.</div></div><div class="quit-ring"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="quit-track" cx="60" cy="60" r="54"></circle><circle id="quitProgress" class="quit-progress" cx="60" cy="60" r="54"></circle></svg><div id="quitTime" class="quit-time"><b>${lastSmoke()?`${String(p.h).padStart(2,'0')}:${String(p.m).padStart(2,'0')}`:'–:–'}</b><span>${lastSmoke()?'Std : Min':'Noch kein Eintrag'}</span></div></div></div><div class="hero-actions"><button id="heroSmoke" class="hero-btn smoke" type="button">+ Zigarette geraucht</button><button id="heroResist" class="hero-btn resist" type="button">🛡 Schmacht überstanden</button></div><button id="heroAdjust" class="hero-link" type="button">Nachträglich eintragen / Zeitpunkt anpassen</button>`}
function renderKpis(){const count=todaySmokes().length,res=todayResists().length,t=target(),p=q('#kpiToday'),a=q('#kpiAvoid');if(p)p.innerHTML=`<div class="kpi-label">Heute</div><div class="kpi-value">${count}${t?` / ${t}`:''}</div><div class="kpi-sub">${t?(count<=t?`${t-count} bis zu deinem Tagesziel`:`${count-t} über deinem Tagesziel`):'Dein heutiger Zähler.'}</div>${t?`<div class="mini-track"><span style="width:${Math.min(100,count/t*100)}%"></span></div>`:''}`;if(a)a.innerHTML=`<div class="kpi-label">Vermiedene Impulse</div><div class="kpi-value">${res}</div><div class="kpi-sub">Jede bewusst überstandene Schmachtphase zählt als eigener Erfolg.</div>`}
function renderLab(){const st=stats(),box=q('#labInsight');if(!box)return;if(st.n<8){const n=Math.min(7,st.n),pct=Math.min(100,Math.round(n/7*100));box.innerHTML=`<div class="lab-head"><b>Lab-Erkenntnis</b><span class="lab-badge">${n} / 7</span></div><div class="lab-copy">Noch <strong>${Math.max(0,8-st.n)}</strong> ${8-st.n===1?'Situation':'Situationen'} bis Smoke Lab genug Daten für ein erstes belastbares Muster hat.</div><div class="mini-track"><span style="width:${pct}%"></span></div>`}else{const top=st.top,pct=top?Math.round(top[1]/st.n*100):0;box.innerHTML=`<div class="lab-head"><b>Lab-Erkenntnis</b><span class="lab-badge">Muster aktiv</span></div><div class="lab-copy">Dein häufigster Auslöser ist aktuell <strong>${top?.[0]||'noch nicht eindeutig'}</strong>${top?` und taucht in ${pct}% der erfassten Situationen auf.`:'.'}</div>`}}
function renderDash(){ensureShell();renderHero();renderKpis();renderLab();updateLive()}
function updateLive(){const p=sinceParts(),t=q('#quitTime b'),ring=q('#quitProgress');if(t)t.textContent=lastSmoke()?`${String(p.h).padStart(2,'0')}:${String(p.m).padStart(2,'0')}`:'–:–';if(ring)ring.style.strokeDashoffset=String(339.292*(1-progressCycle()));if(lastSmoke()){const mins=Math.floor(sinceMs()/60000),milestone=[30,60,120,240,480,720,1440].filter(x=>mins>=x).at(-1)||0;if(milestone&&milestone!==lastMilestone){lastMilestone=milestone;t?.parentElement?.classList.add('milestone-glow');setTimeout(()=>t?.parentElement?.classList.remove('milestone-glow'),1300)}}}
function quickTimestamp(){const now=Date.now();if(quickTimeMode==='15')return now-900000;if(quickTimeMode==='30')return now-1800000;if(quickTimeMode==='custom'&&quickCustom){const[h,m]=quickCustom.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);return d.getTime()}return now}
function openQuick(mode='smoke',adjust=false){quickMode=mode;quickTrigger=null;quickIntensity=3;quickTimeMode=adjust?'custom':'now';quickTimeOpen=adjust;if(adjust){const d=new Date();quickCustom=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}else quickCustom='';renderQuick();q('#quickSheetOverlay')?.classList.add('open')}
function closeQuick(){quickTimeOpen=false;q('#quickSheetOverlay')?.classList.remove('open')}
function renderQuick(){const sheet=q('#quickSheet');if(!sheet)return;const title=quickMode==='smoke'?'Zigarette erfassen':'Schmacht überstanden';sheet.innerHTML=`<div class="qs-head"><div><div class="eyebrow">SCHNELLER EINTRAG</div><div class="qs-title">${title}</div></div><button id="qsTimeBtn" class="qs-time" type="button">⏱️ ${quickTimeMode==='15'?'-15 Min':quickTimeMode==='30'?'-30 Min':quickTimeMode==='custom'?(quickCustom||'Uhrzeit'):'Jetzt'}</button></div><div id="qsTimeArea"></div><div><div class="eyebrow">AUSLÖSER</div><div class="qs-grid">${[['Stress / Überlastung','Stress'],['Pause / Leerlauf','Pause'],['Sozial / Gesellschaft','Gesellschaft'],['Pause / Leerlauf','Langeweile']].map(([v,l])=>`<button class="qs-chip ${quickTrigger===v?'selected':''}" data-qs-trigger="${v}" type="button">${l}</button>`).join('')}</div></div><div><div class="eyebrow">STÄRKE</div><div class="qs-intensity">${[1,2,3,4,5].map(n=>`<button class="${quickIntensity===n?'selected':''}" data-qs-intensity="${n}" type="button">${n}</button>`).join('')}</div></div><div class="qs-actions"><button id="qsCancel" class="qs-btn" type="button">Abbrechen</button><button id="qsSave" class="qs-btn primary" type="button">Speichern</button></div>`;if(quickTimeOpen)renderTimeArea()}
function renderTimeArea(){const area=q('#qsTimeArea');if(!area)return;area.innerHTML=`<div class="qs-time-pop"><button data-qs-time="now" type="button">Jetzt</button><button data-qs-time="15" type="button">-15 Min</button><button data-qs-time="30" type="button">-30 Min</button><input id="qsCustomTime" type="time" value="${quickCustom||''}" aria-label="Eigene Uhrzeit"></div>`}
function saveQuick(){const ts=quickTimestamp(),trigger=quickTrigger||null,intensity=quickIntensity;if(quickMode==='smoke'){atomic(d=>{d.smokes.push({ts,trigger,need:null,intensity});if(!d.startedAt)d.startedAt=Date.now()})}else{atomic(d=>d.resists.push({ts,source:'manual',trigger,intensity}));if(typeof hapticSuccess==='function')hapticSuccess()}closeQuick();renderAll();renderDash();const btn=q(quickMode==='smoke'?'#heroSmoke':'#heroResist');btn?.classList.add('saved');setTimeout(()=>btn?.classList.remove('saved'),380);toast(quickMode==='smoke'?'Zigarette erfasst.':'Schmacht als überstanden erfasst.');if(navigator.vibrate)navigator.vibrate(35)}
document.addEventListener('click',e=>{if(e.target.closest('#heroSmoke')){openQuick('smoke');return}if(e.target.closest('#heroResist')){openQuick('resist');return}if(e.target.closest('#heroAdjust')){openQuick('smoke',true);return}if(e.target.closest('#qsCancel')){closeQuick();return}if(e.target.closest('#qsSave')){saveQuick();return}if(e.target.id==='qsTimeBtn'){quickTimeOpen=!quickTimeOpen;renderQuick();return}const tm=e.target.closest('[data-qs-time]');if(tm){quickTimeMode=tm.dataset.qsTime;quickTimeOpen=false;renderQuick();return}const tr=e.target.closest('[data-qs-trigger]');if(tr){quickTrigger=tr.dataset.qsTrigger;renderQuick();return}const it=e.target.closest('[data-qs-intensity]');if(it){quickIntensity=+it.dataset.qsIntensity;renderQuick();return}if(e.target.id==='quickSheetOverlay')closeQuick()},true);
document.addEventListener('change',e=>{if(e.target.id==='qsCustomTime'){quickCustom=e.target.value;quickTimeMode='custom';quickTimeOpen=false;renderQuick()}},true);
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderDash()};ensureShell();renderDash();requestAnimationFrame(function live(){updateLive();requestAnimationFrame(live)});
})();
