'use strict';
(()=>{
const q=(s,r=document)=>r.querySelector(s);let lastMilestone=0,quickMode='smoke',quickTriggerKey=null,quickIntensity=3,quickTimeMode='now',quickCustom='';
const TRIGGERS={stress:{icon:'⚡',label:'Stress',value:'Stress / Überlastung'},pause:{icon:'☕',label:'Pause',value:'Pause / Leerlauf'},social:{icon:'👥',label:'Gesellschaft',value:'Sozial / Gesellschaft'},bored:{icon:'🥱',label:'Langeweile',value:'Pause / Leerlauf'}};
const shortTrigger=name=>name==='Sozial / Gesellschaft'?'Gesellschaft':name==='Stress / Überlastung'?'Stress':name==='Pause / Leerlauf'?'Pause':name;
function todaySmokes(){return S.smokes.filter(x=>sameDay(x.ts,new Date())).sort((a,b)=>b.ts-a.ts)}
function todayResists(){return S.resists.filter(x=>sameDay(x.ts,new Date()))}
function lastSmoke(){return [...S.smokes].sort((a,b)=>a.ts-b.ts).at(-1)||null}
function sinceMs(){const x=lastSmoke();return x?Math.max(0,Date.now()-x.ts):0}
function sinceParts(){const ms=sinceMs(),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return{h,m}}
function progressCycle(){if(!lastSmoke())return 0;return Math.min(1,(sinceMs()%(4*3600000))/(4*3600000))}
function ensureShell(){const home=document.getElementById('home');if(!home||q('.dash-v2',home))return;[...home.children].forEach(el=>el.classList.add('original-home-v1'));const shell=document.createElement('div');shell.className='dash-v2';shell.innerHTML='<section id="quitHero" class="quit-hero"></section><div class="kpi-grid"><section id="kpiToday" class="kpi-card"></section><section id="kpiAvoid" class="kpi-card"></section></div><section id="labInsight" class="lab-card"></section>';home.prepend(shell);const ov=document.createElement('div');ov.id='quickSheetOverlay';ov.className='quick-sheet-overlay';ov.innerHTML='<div id="quickSheet" class="quick-sheet" role="dialog" aria-modal="true"></div>';document.body.appendChild(ov)}
function renderHero(){const p=sinceParts(),hero=q('#quitHero'),has=Boolean(lastSmoke());if(!hero)return;hero.innerHTML=`<div class="quit-top"><div class="quit-copy"><div class="eyebrow">RAUCHFREI-TRACKER</div><div class="quit-title">Zeit seit der letzten Zigarette</div><div class="quit-sub">${has?'Dein aktueller Abstand auf einen Blick.':'Bereit für Tag 1.'}</div></div><div class="quit-ring"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="quit-track" cx="60" cy="60" r="54"></circle><circle id="quitProgress" class="quit-progress" cx="60" cy="60" r="54"></circle></svg><div id="quitTime" class="quit-time"><b>${has?`${String(p.h).padStart(2,'0')}:${String(p.m).padStart(2,'0')}`:'Start'}</b><span>${has?'Std : Min':'Tag 1'}</span></div></div></div><div class="hero-actions"><button id="heroSmoke" class="hero-btn smoke" type="button">+ Zigarette erfassen</button><button id="heroResist" class="hero-btn resist" type="button">Rauchdrang widerstanden</button></div>`}
function renderKpis(){const count=todaySmokes().length,res=todayResists().length,p=q('#kpiToday'),a=q('#kpiAvoid');if(p)p.innerHTML=`<div class="kpi-label">Heute</div><div class="kpi-value">${count}</div><div class="kpi-sub">Erfasste Zigaretten heute.</div>`;if(a)a.innerHTML=`<div class="kpi-label">Widerstanden</div><div class="kpi-value">${res}</div><div class="kpi-sub">Bewusst nicht gerauchte Situationen heute.</div>`}
function renderLab(){const st=stats(),box=q('#labInsight');if(!box)return;if(st.n<7){const n=st.n,remain=7-n,pct=Math.round(n/7*100);box.innerHTML=`<div class="lab-head"><b>Lab-Erkenntnis</b><span class="lab-badge">${n} / 7</span></div><div class="lab-copy">${n===0?'Deine ersten Einträge füllen die Muster-Matrix sofort.':`Noch <strong>${remain}</strong> ${remain===1?'Situation':'Situationen'} bis zur vollständigen Muster-Matrix.`}</div><div class="mini-track"><span style="width:${pct}%"></span></div>`}else{const top=st.top,pct=top?Math.round(top[1]/st.n*100):0;box.innerHTML=`<div class="lab-head"><b>Lab-Erkenntnis</b><span class="lab-badge">Muster aktiv</span></div><div class="lab-copy">Dein häufigster Auslöser ist aktuell <strong>${shortTrigger(top?.[0]||'noch nicht eindeutig')}</strong>${top?` und taucht in ${pct}% der erfassten Situationen auf.`:'.'}</div>`}}
function renderDash(){ensureShell();renderHero();renderKpis();renderLab();updateLive()}
function updateLive(){const p=sinceParts(),t=q('#quitTime b'),ring=q('#quitProgress');if(t)t.textContent=lastSmoke()?`${String(p.h).padStart(2,'0')}:${String(p.m).padStart(2,'0')}`:'Start';if(ring)ring.style.strokeDashoffset=String(339.292*(1-progressCycle()));if(lastSmoke()){const mins=Math.floor(sinceMs()/60000),milestone=[30,60,120,240,480,720,1440].filter(x=>mins>=x).at(-1)||0;if(milestone&&milestone!==lastMilestone){lastMilestone=milestone;t?.parentElement?.classList.add('milestone-glow');setTimeout(()=>t?.parentElement?.classList.remove('milestone-glow'),1300)}}}
function quickTimestamp(){const now=Date.now();if(quickTimeMode==='15')return now-900000;if(quickTimeMode==='30')return now-1800000;if(quickTimeMode==='custom'&&quickCustom){const[h,m]=quickCustom.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);return d.getTime()}return now}
function openQuick(mode='smoke'){quickMode=mode;quickTriggerKey=null;quickIntensity=3;quickTimeMode='now';quickCustom='';renderQuick();q('#quickSheetOverlay')?.classList.add('open')}
function closeQuick(){q('#quickSheetOverlay')?.classList.remove('open')}
function renderQuick(){const sheet=q('#quickSheet');if(!sheet)return;const title=quickMode==='smoke'?'Zigarette erfassen':'Rauchdrang widerstanden';sheet.innerHTML=`<div class="qs-scroll"><div class="qs-head"><div><div class="eyebrow">SCHNELLER EINTRAG</div><div class="qs-title">${title}</div></div></div><div class="qs-section"><div class="eyebrow">ZEITPUNKT</div><div class="qs-segmented">${[['now','Jetzt'],['15','−15m'],['30','−30m'],['custom','🕒 Frei']].map(([v,l])=>`<button class="${quickTimeMode===v?'active':''}" data-qs-time="${v}" type="button">${l}</button>`).join('')}</div>${quickTimeMode==='custom'?`<div class="qs-custom-time"><input id="qsCustomTime" type="time" value="${quickCustom||''}" aria-label="Freie Uhrzeit"></div>`:''}</div><div class="qs-section"><div class="eyebrow">AUSLÖSER</div><div class="qs-grid">${Object.entries(TRIGGERS).map(([k,x])=>`<button class="qs-chip ${quickTriggerKey===k?'selected':''}" data-qs-trigger="${k}" type="button"><span>${x.icon}</span>${x.label}</button>`).join('')}</div></div><div class="qs-section"><div class="eyebrow">STÄRKE</div><div class="qs-intensity">${[1,2,3,4,5].map(n=>`<button class="${quickIntensity===n?'selected':''}" data-qs-intensity="${n}" type="button">${n}</button>`).join('')}</div></div></div><div class="qs-actions"><button id="qsCancel" class="qs-btn" type="button">Abbrechen</button><button id="qsSave" class="qs-btn primary" type="button">Speichern</button></div>`}
function saveQuick(){const ts=quickTimestamp(),trigger=quickTriggerKey?TRIGGERS[quickTriggerKey].value:null,intensity=quickIntensity;if(quickMode==='smoke'){atomic(d=>{d.smokes.push({ts,trigger,need:null,intensity});if(!d.startedAt)d.startedAt=Date.now()})}else{atomic(d=>d.resists.push({ts,source:'manual',trigger,intensity}));if(typeof hapticSuccess==='function')hapticSuccess()}closeQuick();renderAll();renderDash();const btn=q(quickMode==='smoke'?'#heroSmoke':'#heroResist');btn?.classList.add('saved');setTimeout(()=>btn?.classList.remove('saved'),380);toast(quickMode==='smoke'?'Zigarette erfasst.':'Rauchdrang als widerstanden erfasst.');if(navigator.vibrate)navigator.vibrate(35)}
function triggerRows(){const st=stats(),entries=st.sorted.length?st.sorted:RISKS.map(x=>[x,0]);const max=Math.max(1,...entries.map(x=>x[1]));return entries.slice(0,6).map(([name,n])=>`<div class="cal-row"><div class="cal-label"><span>${shortTrigger(name)}</span><strong>${n}×</strong></div><div class="cal-track"><span style="width:${n/max*100}%"></span></div></div>`).join('')}
renderPatterns=function(){const st=stats(),n=Math.min(7,st.n),remain=Math.max(0,7-st.n),pct=Math.min(100,Math.round(st.n/7*100));patternsCard.innerHTML=`<div class="cal-dashboard"><div class="cal-head"><div><div class="eyebrow">MUSTER-MATRIX</div><div class="h2">${st.n<7?'Kalibrierungs-Phase':'Deine ersten Muster'}</div></div><span class="lab-badge">${n} / 7</span></div><div class="cal-progress-copy"><span>${st.n<7?`${remain} ${remain===1?'Situation':'Situationen'} bis zur vollständigen Matrix`:'Matrix freigeschaltet'}</span><strong>${pct}%</strong></div><div class="mini-track"><span style="width:${pct}%"></span></div><div class="cal-block"><div class="eyebrow">ERSTE TENDENZEN</div>${triggerRows()}</div>${st.top?`<div class="cal-note">Aktuell am häufigsten: <strong>${shortTrigger(st.top[0])}</strong> (${st.top[1]}×).</div>`:`<div class="cal-note">Noch keine Daten. Dein erster Eintrag erscheint hier sofort.</div>`}</div>`}
ensureExperiment=function(){const st=stats();if(st.n<7||!st.top)return null;const trigger=st.top[0],cfg=interventionConfig(trigger),today=todayKey();if(!S.experiment||S.experiment.trigger!==trigger){S.experiment={trigger,family:cfg.family,title:cfg.title,task:cfg.task,startDate:today,day:1,goal:2,progress:0,history:[]};persist()}const elapsed=dayDiff(S.experiment.startDate,today),day=Math.min(3,elapsed+1);if(day>S.experiment.day){S.experiment.history=S.experiment.history||[];S.experiment.history.push({day:S.experiment.day,progress:S.experiment.progress,goal:S.experiment.goal});S.experiment.day=day;S.experiment.progress=0;persist()}restoreExperimentMirror();return S.experiment}
renderExperiment=function(){const st=stats();if(st.n<7){const remain=7-st.n;experimentCard.innerHTML=`<div class="experiment-teaser"><div class="experiment-teaser-head"><div><div class="eyebrow">EXPERIMENT-LABOR</div><div class="h2">Wird nach 7 Situationen freigeschaltet</div></div><span class="lab-badge">${st.n} / 7</span></div><div class="muted">Noch ${remain} ${remain===1?'Situation':'Situationen'}. Danach schlägt Smoke Lab ein Experiment passend zu deinem stärksten Muster vor.</div><div class="preview-grid"><div class="preview-card"><div class="preview-top"><span>Experiment #1</span><em>🔒 Phase 2</em></div><b>5-Minuten-Aufschub</b><small>Den ersten Impuls bewusst verzögern.</small></div><div class="preview-card"><div class="preview-top"><span>Experiment #2</span><em>🔒 Phase 2</em></div><b>Ritual entkoppeln</b><small>Eine typische Rauchsituation durch eine andere Handlung unterbrechen.</small></div></div></div>`;return}const e=ensureExperiment(),p=Math.min(e.goal,e.progress||0),done=p>=e.goal;experimentCard.innerHTML=`<div class="experiment-status"><div><div class="eyebrow">3-TAGE-EXPERIMENT · TAG ${e.day}/3</div><div class="h2">${e.title}</div></div><span class="badge ${done?'done':''}">${done?`Tag ${e.day} gemeistert! 🎉`:'Aktiv'}</span></div><div class="experiment-task">${e.task}</div><div class="progress-row"><span>${done?'Tagesziel erreicht ✓':'Fortschritt heute'}</span><span>${p}/${e.goal}</span></div><div class="track"><div class="fill" style="width:${Math.round(p/e.goal*100)}%"></div></div><button class="manual-win" data-manual-win ${done?'disabled':''} type="button">+ Ich habe der Situation widerstanden</button><div class="muted">Passende erfolgreiche Craving-Stopper erhöhen diesen Zähler automatisch.</div>`}
document.addEventListener('click',e=>{if(e.target.closest('#heroSmoke')){openQuick('smoke');return}if(e.target.closest('#heroResist')){openQuick('resist');return}if(e.target.closest('#qsCancel')){closeQuick();return}if(e.target.closest('#qsSave')){saveQuick();return}const tm=e.target.closest('[data-qs-time]');if(tm){quickTimeMode=tm.dataset.qsTime;if(quickTimeMode==='custom'&&!quickCustom){const d=new Date();quickCustom=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}renderQuick();return}const tr=e.target.closest('[data-qs-trigger]');if(tr){quickTriggerKey=tr.dataset.qsTrigger;renderQuick();return}const it=e.target.closest('[data-qs-intensity]');if(it){quickIntensity=+it.dataset.qsIntensity;renderQuick();return}if(e.target.id==='quickSheetOverlay')closeQuick()},true);
document.addEventListener('change',e=>{if(e.target.id==='qsCustomTime'){quickCustom=e.target.value;quickTimeMode='custom';renderQuick()}},true);
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderDash()};ensureShell();renderDash();renderPatterns();renderExperiment();requestAnimationFrame(function live(){updateLive();requestAnimationFrame(live)});
})();