const KEY='smokeLab.v55';
const TRIGGERS=['Stress','Kaffee','Gewohnheit','Pause','Nach dem Essen','Gesellschaft'];
const PHASES=[
 {name:'Beobachten',sub:'Muster sichtbar machen',goal:'Erkennen, wann und warum der Autopilot startet.',task:'Heute zwei Situationen erfassen – ohne sie bewerten zu müssen.',experiments:[['conscious','Bewusste Zigarette','Eine Situation bewusst beobachten und danach erfassen.','log'],['coffee','Kaffee-Test','Beim nächsten Kaffee Trigger und Stärke dokumentieren.','log'],['morning','Morning Check','Den ersten starken Drang des Tages bewusst erfassen.','log']]},
 {name:'Unterbrechen',sub:'Autopilot stören',goal:'Zwischen Trigger und Reaktion einen kleinen Zwischenraum schaffen.',task:'Heute mindestens einmal einen Drang bewusst unterbrechen.',experiments:[['delay','3-Minuten-Delay','Die Reaktion kurz verschieben und danach neu entscheiden.','sos'],['location','Ort wechseln','Beim Trigger bewusst den Ort wechseln.','sos'],['meal','After-Meal Reset','Nach dem Essen zuerst Wasser oder Ortswechsel.','sos']]},
 {name:'Entkoppeln',sub:'Trigger lösen',goal:'Gewohnte Trigger von der Zigarette trennen.',task:'Heute einen bekannten Trigger absichtlich anders beantworten.',experiments:[['coffee2','Coffee Breaker','Kaffee an einem anderen Ort trinken.','sos'],['hands','Hands Busy','Hände für einen Moment anders beschäftigen.','sos'],['break','Work-Break Test','Eine Pause ohne automatische Zigarette testen.','sos']]},
 {name:'Ersetzen',sub:'Neue Antworten testen',goal:'Für häufige Trigger passende Alternativen aufbauen.',task:'Heute bewusst eine neue Antwort auf einen Trigger testen.',experiments:[['water','Wasser-Reset','Bei einem Drang zuerst Wasser holen.','sos'],['walk','Micro-Walk','Ein paar Schritte gehen, bevor du neu entscheidest.','sos'],['switch','Routine Switch','Einen festen Ablauf gezielt verändern.','sos']]},
 {name:'Stabilisieren',sub:'Kontrolle festigen',goal:'Die wirksamsten Strategien gezielt wiederholen.',task:'Heute deine bisher stärkste Strategie erneut einsetzen.',experiments:[['best','Best Strategy','Deine bisher beste Unterbrechung wiederholen.','sos'],['risk','Risk Window','Ein typisches Risikofenster bewusst vorbereiten.','sos'],['choice','Conscious Choice','Vor einer Entscheidung kurz Trigger und Ziel prüfen.','log']]}
];
const SOS_TEXT={Stress:['Druck unterbrechen','Lockere Kiefer und Schultern. Wechsle kurz den Ort oder geh ein paar Schritte.'],Kaffee:['Ritual trennen','Stell den Kaffee kurz weg, trink Wasser und nimm ihn an einem anderen Platz wieder auf.'],Gewohnheit:['Autopilot stören','Ändere nur einen Teil der Reihenfolge: Ort, Hand oder nächste Handlung.'],Pause:['Pause neu besetzen','Steh kurz auf und tu für einen Moment etwas anderes mit deinen Händen.'],'Nach dem Essen':['Übergang verändern','Steh direkt auf, trink Wasser und wechsel den Raum.'],Gesellschaft:['Sozialen Sog lösen','Bleib einen Moment ohne mitzugehen, wechsel Gespräch oder Platz und entscheide danach neu.']};
const fresh=()=>({startedAt:Date.now(),name:'',baseline:10,goal:'quit',events:[],activeTab:'today',onboardingCompleted:false,labDone:[],activeExperiment:null});
let S=load(),draft={type:'smoke',trigger:'Stress',intensity:3},sos={trigger:null};
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function day(){return Math.max(1,Math.min(30,Math.floor((Date.now()-S.startedAt)/86400000)+1))}
function phase(){return Math.min(4,Math.floor((day()-1)/6))}
function phaseStart(i){return i*6+1} function phaseEnd(i){return i*6+6}
function todays(){const d=new Date().toDateString();return S.events.filter(e=>new Date(e.ts).toDateString()===d)}
function smokesToday(){return todays().filter(e=>e.type==='smoke').length}
function resistsToday(){return todays().filter(e=>e.type==='resist').length}
function score(){const a=S.events.slice(-20);if(!a.length)return 50;return Math.round(a.reduce((n,e)=>n+(e.type==='resist'?100:Math.max(20,80-(e.intensity||3)*10)),0)/a.length)}
function topTrigger(){const c={};S.events.forEach(e=>{if(e.trigger)c[e.trigger]=(c[e.trigger]||0)+1});return Object.entries(c).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Noch nicht belastbar'}
function greeting(){const h=new Date().getHours();return h<11?'Guten Morgen':h>17?'Guten Abend':'Guten Tag'}
function toastMsg(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)}
function doneCount(i){return PHASES[i].experiments.filter(x=>S.labDone.includes(x[0])).length}
function render(){renderToday();renderLab();renderPatterns();renderProgress();renderMe();document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===S.activeTab));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===S.activeTab));if(!S.onboardingCompleted)renderOnboarding()}
function renderToday(){today.innerHTML=`<div class="head"><div class="kicker">HEUTE · TAG ${day()}</div><h1>${greeting()}${S.name?`, ${esc(S.name)}`:''}</h1><div class="muted">Verstehe den Trigger. Unterbrich das Muster.</div></div><div class="card status"><div class="row"><div><div class="kicker">PHASE ${phase()+1}</div><h2>${PHASES[phase()].name}</h2></div><span class="badge">${score()}/100</span></div><div class="muted">${PHASES[phase()].sub}</div></div><div class="stack"><button class="btn primary" data-open-log>+ Zigarette / Widerstand erfassen</button><button class="btn petrol" data-open-sos>⚡ Drang stoppen (SOS)</button></div><div class="card stack"><div><div class="kicker">TAGES-RADAR</div><h2 style="font-size:17px;margin-top:4px">Heute auf einen Blick</h2></div><div class="grid2"><div class="metric"><span>Zigaretten</span><strong>${smokesToday()}</strong></div><div class="metric"><span>Unterbrechungen</span><strong>${resistsToday()}</strong></div></div><div class="row"><span class="muted">Muster</span><strong style="font-size:13px;color:var(--ink)">${esc(topTrigger())}</strong></div><div class="row"><span class="muted">Labor</span><strong style="font-size:13px;color:var(--ink)">${doneCount(phase())}/3 Experimente</strong></div></div>`}
function renderLab(){lab.innerHTML=`<div class="head"><div class="kicker">LABOR · 30-TAGE-PROGRAMM</div><h1>Trainiere Kontrolle.</h1><div class="muted">Neue Phasen öffnen sich erst, wenn du zeitlich dort angekommen bist.</div></div><div class="card lab-hero"><div class="row"><div><div class="kicker">AKTUELLE PHASE</div><h2>${PHASES[phase()].name}</h2></div><span class="pill">TAG ${day()}</span></div><div class="body">${PHASES[phase()].task}</div><div class="lab-progress"><span style="width:${doneCount(phase())/3*100}%"></span></div><div class="muted">${doneCount(phase())}/3 Experimente abgeschlossen</div></div><div class="phase-list">${PHASES.map((p,i)=>{const locked=i>phase(),past=i<phase();return `<div class="card phase ${i===phase()?'active':''} ${locked?'locked':''} ${past?'complete':''}" ${locked?'':`data-phase="${i}"`}><div class="phase-num">${locked?'◦':i+1}</div><div><strong>${p.name}</strong><small>${locked?`Öffnet an Tag ${phaseStart(i)}`:p.sub}</small></div><span class="pill">${locked?'GESPERRT':i===phase()?'AKTIV':`${doneCount(i)}/3`}</span></div>`}).join('')}</div>`}
function openPhase(i){const p=PHASES[i];if(i>phase())return;const current=i===phase();openSheet(`<div class="sheethead"><div><div class="kicker">PHASE ${i+1} · TAG ${phaseStart(i)}–${phaseEnd(i)}</div><h2>${p.name}</h2></div><button class="close" data-close>×</button></div><div class="stack"><div class="card stack"><div><div class="kicker">ZIEL</div><div class="body" style="margin-top:5px">${p.goal}</div></div>${current?`<div><div class="kicker">HEUTE</div><div class="body" style="margin-top:5px">${p.task}</div></div>`:`<div class="muted">Diese Phase liegt bereits hinter dir. Du kannst deine Experimente hier weiterhin ansehen.</div>`}</div><div><div class="kicker" style="margin-bottom:8px">EXPERIMENTE</div><div class="exp-list">${p.experiments.map(x=>{const done=S.labDone.includes(x[0]);return `<div class="card exp-item"><div><strong>${x[1]}</strong><small>${x[2]}</small></div>${done?`<span class="check">✓</span>`:current?`<button class="pill" data-exp="${x[0]}" data-exp-mode="${x[3]}">Starten</button>`:`<span class="pill">offen</span>`}</div>`}).join('')}</div></div></div>`)}
function renderPatterns(){const n=S.events.length;patterns.innerHTML=`<div class="head"><div class="kicker">MUSTER</div><h1>Dein Rauchmuster.</h1><div class="muted">Erst Daten sammeln, dann Muster behaupten.</div></div><div class="card stack"><div class="row"><span class="kicker">KALIBRIERUNG</span><strong>${Math.min(n,8)}/8</strong></div><div class="progressbar"><span style="width:${Math.min(100,n/8*100)}%"></span></div>${n<8?`<div class="pattern-grid"><div class="card pattern-item"><strong>Trigger</strong><span>Noch nicht belastbar</span></div><div class="card pattern-item"><strong>Zeitfenster</strong><span>Noch nicht belastbar</span></div><div class="card pattern-item"><strong>Intensität</strong><span>Noch nicht belastbar</span></div><div class="card pattern-item"><strong>Kontext</strong><span>Noch nicht belastbar</span></div></div>`:`<div class="pattern-grid"><div class="card pattern-item"><strong>Top-Trigger</strong><span>${esc(topTrigger())}</span></div><div class="card pattern-item"><strong>Situationen</strong><span>${n} dokumentiert</span></div></div>`}</div>`}
function renderProgress(){const days=[6,5,4,3,2,1,0].map(off=>{const d=new Date();d.setDate(d.getDate()-off);return S.events.filter(e=>new Date(e.ts).toDateString()===d.toDateString()).length});const max=Math.max(...days,1);progress.innerHTML=`<div class="head"><div class="kicker">FORTSCHRITT</div><h1>Kontrolle statt Erfolgsserien.</h1><div class="muted">Mehr Wahlmöglichkeit, nicht perfekte Tage.</div></div><div class="card stack"><div class="kicker">KONTROLLWERT</div><div class="row"><div><div style="font-size:48px;line-height:.95;font-weight:800;color:var(--ink)">${score()}</div><div class="muted">aus deinen letzten Situationen</div></div><span class="pill">Referenz ${S.baseline}/Tag</span></div></div><div class="grid2"><div class="metric"><span>Unterbrechungen</span><strong>${S.events.filter(e=>e.type==='resist').length}</strong></div><div class="metric"><span>Erfasst</span><strong>${S.events.filter(e=>e.type==='smoke').length}</strong></div><div class="metric"><span>Heute</span><strong>${smokesToday()}</strong></div><div class="metric"><span>Labor</span><strong>${S.labDone.length}</strong></div></div><div class="card stack"><div class="kicker">7-TAGE-TREND</div><div class="chart">${days.map((v,i)=>`<div class="barwrap"><div class="bar ${i===6?'today':''}" style="height:${Math.max(8,Math.round(v/max*76))}px"></div><small>${i===6?'Heute':6-i+'T'}</small></div>`).join('')}</div></div>`}
function renderMe(){me.innerHTML=`<div class="head"><div class="kicker">ICH</div><h1>Deine Einstellungen.</h1><div class="muted">Alles lokal auf diesem Gerät.</div></div><div class="card"><div class="setting"><strong>Name</strong><small>${esc(S.name||'Nicht gesetzt')}</small></div><div class="setting"><strong>Ziel</strong><small>${S.goal==='quit'?'Aufhören':'Reduzieren'}</small></div><div class="setting"><strong>Ausgangswert</strong><small>${S.baseline} Zigaretten / Tag</small></div><div class="setting"><strong>Programm</strong><small>Tag ${day()} · Phase ${phase()+1}</small></div></div><button class="btn ghost" data-edit-profile>Profil bearbeiten</button><button class="btn ghost" data-reset>App zurücksetzen</button>`}
function renderOnboarding(){onboarding.classList.add('open');onboarding.innerHTML=`<div class="head"><div class="kicker">SMOKE LAB</div><h1>Verstehe den Trigger. Unterbrich das Muster.</h1><div class="muted">Kurzes Setup – deine Daten bleiben lokal auf deinem Gerät.</div></div><div class="card stack"><label class="kicker">DEIN VORNAME</label><input class="input" id="obName" value="${esc(S.name)}" placeholder="Vorname"><label class="kicker">ZIGARETTEN PRO TAG</label><input class="input" id="obBase" type="number" min="1" max="80" value="${S.baseline}"><label class="kicker">DEIN ZIEL</label><div class="goal-grid"><button class="goal ${S.goal==='quit'?'active':''}" data-goal="quit">Aufhören</button><button class="goal ${S.goal==='reduce'?'active':''}" data-goal="reduce">Reduzieren</button></div></div><button class="btn petrol" data-start>Smoke Lab starten</button>`}
function openSheet(html){sheet.innerHTML=html;backdrop.classList.add('open');requestAnimationFrame(()=>sheet.classList.add('open'))}function closeSheet(){sheet.classList.remove('open');backdrop.classList.remove('open')}
function openLog(){draft={type:'smoke',trigger:'Stress',intensity:3};openSheet(`<div class="sheethead"><div><div class="kicker">ERFASSEN</div><h2>Zigarette / Widerstand</h2></div><button class="close" data-close>×</button></div><div class="stack"><div class="seg"><button class="active" data-type="smoke">Geraucht</button><button data-type="resist">Widerstanden</button></div><div><div class="kicker" style="margin-bottom:8px">AUSLÖSER</div><div class="trigger-grid">${TRIGGERS.map((t,i)=>`<button class="trigger ${i===0?'active':''}" data-trigger="${t}">${t}</button>`).join('')}</div></div><div><div class="row"><span class="kicker">STÄRKE</span><strong id="strengthVal">3/5</strong></div><input class="slider" id="strength" type="range" min="1" max="5" value="3"><div class="sliderlabels"><span>leicht</span><span>stark</span></div></div><button class="btn primary" data-save-log>Speichern</button></div>`)}
function openSOS(){openSheet(`<div class="sheethead"><div><div class="kicker">SOS</div><h2>Was triggert dich gerade?</h2></div><button class="close" data-close>×</button></div><div class="trigger-grid">${TRIGGERS.map(t=>`<button class="trigger" data-sos-trigger="${t}">${t}</button>`).join('')}</div>`)}
function showSOS(t){sos.trigger=t;const [title,copy]=SOS_TEXT[t];openSheet(`<div class="sheethead"><div><div class="kicker">MIKRO-INTERVENTION</div><h2>${title}</h2></div><button class="close" data-close>×</button></div><div class="card"><div class="body">${copy}</div></div><div class="stack" style="margin-top:16px"><button class="btn petrol" data-sos-down>Gesunken</button><button class="btn ghost" data-close>Noch da</button></div>`)}
function profileSheet(){openSheet(`<div class="sheethead"><div><div class="kicker">PROFIL</div><h2>Einstellungen</h2></div><button class="close" data-close>×</button></div><div class="stack"><label class="kicker">NAME</label><input class="input" id="pfName" value="${esc(S.name)}"><label class="kicker">AUSGANGSWERT</label><input class="input" id="pfBase" type="number" min="1" max="80" value="${S.baseline}"><div class="seg"><button class="${S.goal==='quit'?'active':''}" data-pf-goal="quit">Aufhören</button><button class="${S.goal==='reduce'?'active':''}" data-pf-goal="reduce">Reduzieren</button></div><button class="btn petrol" data-save-profile>Speichern</button></div>`)}
function completeActiveExperiment(){if(S.activeExperiment&&!S.labDone.includes(S.activeExperiment)){S.labDone.push(S.activeExperiment);S.activeExperiment=null;save();toastMsg('Labor-Experiment abgeschlossen ✓')}}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){S.activeTab=tab.dataset.tab;save();render();return}const ph=e.target.closest('[data-phase]');if(ph)return openPhase(Number(ph.dataset.phase));const exp=e.target.closest('[data-exp]');if(exp){S.activeExperiment=exp.dataset.exp;save();closeSheet();return exp.dataset.expMode==='sos'?openSOS():openLog()}if(e.target.closest('[data-open-log]'))return openLog();if(e.target.closest('[data-open-sos]'))return openSOS();if(e.target.closest('[data-close]')||e.target===backdrop)return closeSheet();const typ=e.target.closest('[data-type]');if(typ){draft.type=typ.dataset.type;document.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('active',x===typ));return}const trg=e.target.closest('[data-trigger]');if(trg){draft.trigger=trg.dataset.trigger;document.querySelectorAll('[data-trigger]').forEach(x=>x.classList.toggle('active',x===trg));return}if(e.target.closest('[data-save-log]')){S.events.push({ts:Date.now(),type:draft.type,trigger:draft.trigger,intensity:draft.intensity});completeActiveExperiment();save();closeSheet();render();toastMsg(draft.type==='resist'?'Unterbrechung gespeichert ✓':'Situation gespeichert ✓');return}const st=e.target.closest('[data-sos-trigger]');if(st)return showSOS(st.dataset.sosTrigger);if(e.target.closest('[data-sos-down]')){S.events.push({ts:Date.now(),type:'resist',trigger:sos.trigger,intensity:null,source:'sos'});completeActiveExperiment();save();closeSheet();render();toastMsg('Drang gesunken · Kontrolle +1 ✓');return}const g=e.target.closest('[data-goal]');if(g){S.goal=g.dataset.goal;renderOnboarding();return}if(e.target.closest('[data-start]')){S.name=document.getElementById('obName').value.trim();S.baseline=Math.max(1,Number(document.getElementById('obBase').value)||10);S.onboardingCompleted=true;save();onboarding.classList.remove('open');render();return}if(e.target.closest('[data-edit-profile]'))return profileSheet();const pg=e.target.closest('[data-pf-goal]');if(pg){S.goal=pg.dataset.pfGoal;document.querySelectorAll('[data-pf-goal]').forEach(x=>x.classList.toggle('active',x===pg));return}if(e.target.closest('[data-save-profile]')){S.name=document.getElementById('pfName').value.trim();S.baseline=Math.max(1,Number(document.getElementById('pfBase').value)||10);save();closeSheet();render();toastMsg('Profil gespeichert ✓');return}if(e.target.closest('[data-reset]')){localStorage.removeItem(KEY);S=fresh();render()}});
document.addEventListener('input',e=>{if(e.target.id==='strength'){draft.intensity=Number(e.target.value);document.getElementById('strengthVal').textContent=draft.intensity+'/5'}});
render();